import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { AppSidebar } from '@/shared/components/layout/AppSidebar';
import { SidebarProvider } from '@/shared/components/ui/sidebar';
import { AuthProvider } from '@/shared/context/AuthContext';

const roboto = Roboto({
  variable: '--font-roboto-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Doppler',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${roboto.variable} text-text antialiased`}>
        <AuthProvider>
          <SidebarProvider>
            <AppSidebar />
            <main className="w-full">{children}</main>
          </SidebarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
