import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';

import { AuthProvider } from '@/shared/context/AuthContext';
import { LayoutContent } from '@/shared/components/layout/LayoutContent';

const roboto = Roboto({
  variable: '--font-roboto-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Doppler',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${roboto.variable} text-text antialiased`}>
        <AuthProvider>
          <LayoutContent>
            <main className="w-full">{children}</main>
          </LayoutContent>
        </AuthProvider>
      </body>
    </html>
  );
}
